spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/ms_user
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: 35.199.70.141
    port: 5672
    username: admin
    password: password@vascobank123
  application:
    name: user-management

client:
  log:
    queue: vascobank.logs
